# Generated by Django 5.2.11 on 2026-02-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={"verbose_name": "Бронювання", "verbose_name_plural": "Бронювання"},
        ),
        migrations.AddField(
            model_name="booking",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
