# Generated by Django 5.2.11 on 2026-02-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address_uk", models.TextField(verbose_name="Address (Ukrainian)")),
                ("address_en", models.TextField(verbose_name="Address (English)")),
                ("phone", models.CharField(max_length=50, verbose_name="Phone")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "check_in",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Check-in time"
                    ),
                ),
                (
                    "check_out",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Check-out time"
                    ),
                ),
                (
                    "google_maps_url",
                    models.URLField(blank=True, verbose_name="Google Maps link"),
                ),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
    ]
