# Generated by Django 5.2.11 on 2026-02-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="google_maps_url",
            field=models.TextField(blank=True, verbose_name="Google Maps link"),
        ),
    ]
