# Generated by Django 5.2.11 on 2026-02-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_sitesettings_google_maps_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="city_en",
            field=models.TextField(blank=True, verbose_name="City"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="city_uk",
            field=models.TextField(blank=True, verbose_name="City"),
        ),
    ]
