# Generated by Django 5.2.11 on 2026-02-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_sitesettings_city_en_sitesettings_city_uk"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "twitter",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Twitter (X)"
                    ),
                ),
                (
                    "instagram",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Instagram"
                    ),
                ),
                (
                    "facebook",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Facebook"
                    ),
                ),
                (
                    "linkedin",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Linked In"
                    ),
                ),
            ],
            options={
                "verbose_name": "Social Media",
                "verbose_name_plural": "Social Media",
            },
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="city_en",
            field=models.TextField(blank=True, verbose_name="City (English)"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="city_uk",
            field=models.TextField(blank=True, verbose_name="City (Ukrainian)"),
        ),
    ]
