# Generated by Django 5.2.11 on 2026-02-11 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_socialmedia_alter_sitesettings_city_en_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_uk",
                    models.CharField(max_length=100, verbose_name="Назва (укр)"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=100, verbose_name="Назва (англ)"),
                ),
                (
                    "icon_class",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="CSS іконка (bi class)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Зручність",
                "verbose_name_plural": "Зручності",
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room_name_uk",
                    models.CharField(max_length=200, verbose_name="Назва номера (укр)"),
                ),
                (
                    "room_name_en",
                    models.CharField(
                        max_length=200, verbose_name="Назва номера (англ)"
                    ),
                ),
                ("description_uk", models.TextField(verbose_name="Опис (укр)")),
                ("description_en", models.TextField(verbose_name="Опис (англ)")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Ціна"
                    ),
                ),
                (
                    "discount",
                    models.PositiveIntegerField(default=0, verbose_name="Знижка (%)"),
                ),
                ("square", models.PositiveIntegerField(verbose_name="Площа (м²)")),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        default=2, verbose_name="Кількість гостей"
                    ),
                ),
                (
                    "main_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="rooms/main/",
                        verbose_name="Головне фото",
                    ),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активний"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amenities",
                    models.ManyToManyField(
                        blank=True, to="main.amenity", verbose_name="Зручності"
                    ),
                ),
            ],
            options={
                "verbose_name": "Номер",
                "verbose_name_plural": "Номери",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="BookingRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200, verbose_name="ПІБ")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("phone", models.CharField(max_length=50, verbose_name="Телефон")),
                ("check_in", models.DateField(verbose_name="Дата заїзду")),
                ("check_out", models.DateField(verbose_name="Дата виїзду")),
                (
                    "guests",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Кількість гостей"
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, verbose_name="Додаткове повідомлення"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Нова"),
                            ("contacted", "Зв’язались"),
                            ("confirmed", "Підтверджено"),
                            ("cancelled", "Скасовано"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_requests",
                        to="main.room",
                        verbose_name="Номер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на бронювання",
                "verbose_name_plural": "Заявки на бронювання",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RoomImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="rooms/gallery/", verbose_name="Фото"),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="main.room",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото номера",
                "verbose_name_plural": "Фото номерів",
            },
        ),
    ]
