# Generated by Django 5.2.11 on 2026-02-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_amenity_room_bookingrequest_roomimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="Client's name")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("subject", models.CharField(max_length=200, verbose_name="Subject")),
                ("message", models.TextField(verbose_name="Message")),
            ],
            options={
                "verbose_name": "Повідомлення",
                "verbose_name_plural": "Повідомлення",
            },
        ),
        migrations.DeleteModel(
            name="BookingRequest",
        ),
    ]
