# Generated by Django 5.2.11 on 2026-02-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_contactmessages_delete_bookingrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Name")),
                ("message", models.TextField(verbose_name="Message")),
            ],
            options={
                "verbose_name": "Коментар",
                "verbose_name_plural": "Коментарі",
            },
        ),
        migrations.AlterModelOptions(
            name="sitesettings",
            options={
                "verbose_name": "Настройка сайту",
                "verbose_name_plural": "Настройки сайту",
            },
        ),
        migrations.AlterModelOptions(
            name="socialmedia",
            options={"verbose_name": "Соц-мережі", "verbose_name_plural": "Соц-мережі"},
        ),
    ]
