# Generated by Django 5.2.11 on 2026-02-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_testimonials_alter_sitesettings_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testimonials",
            name="message",
        ),
        migrations.RemoveField(
            model_name="testimonials",
            name="name",
        ),
        migrations.AddField(
            model_name="testimonials",
            name="message_en",
            field=models.TextField(default="", verbose_name="Message_en"),
        ),
        migrations.AddField(
            model_name="testimonials",
            name="message_uk",
            field=models.TextField(default="", verbose_name="Message"),
        ),
        migrations.AddField(
            model_name="testimonials",
            name="name_en",
            field=models.CharField(default="", max_length=30, verbose_name="Name_en"),
        ),
        migrations.AddField(
            model_name="testimonials",
            name="name_uk",
            field=models.CharField(default="", max_length=30, verbose_name="Name"),
        ),
    ]
