# Generated by Django 5.2.11 on 2026-02-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_remove_testimonials_message_remove_testimonials_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="main_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="hotel/", verbose_name="Головне фото"
            ),
        ),
    ]
