# Generated by Django 5.2.11 on 2026-02-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_alter_room_main_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryMainPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "img",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="gal/main/",
                        verbose_name="Фото",
                    ),
                ),
                ("alt", models.CharField(max_length=100, verbose_name="Опис")),
            ],
            options={
                "verbose_name": "Фото головна сторінка",
                "verbose_name_plural": "Фото головна сторінка",
            },
        ),
    ]
