# Generated by Django 5.2.11 on 2026-02-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_gallerymainpage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gallerymainpage",
            name="alt",
        ),
        migrations.AddField(
            model_name="gallerymainpage",
            name="alt_en",
            field=models.CharField(
                default="Photo Wood Life", max_length=100, verbose_name="Опис (en)"
            ),
        ),
        migrations.AddField(
            model_name="gallerymainpage",
            name="alt_uk",
            field=models.CharField(
                default="Фото Wood Life", max_length=100, verbose_name="Опис (укр)"
            ),
        ),
    ]
