# Generated by Django 5.2.11 on 2026-02-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_remove_gallerymainpage_alt_gallerymainpage_alt_en_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "img",
                    models.ImageField(
                        blank=True, null=True, upload_to="gal/gal/", verbose_name="Фото"
                    ),
                ),
                (
                    "alt_uk",
                    models.CharField(
                        default="Фото Wood Life",
                        max_length=100,
                        verbose_name="Опис (укр)",
                    ),
                ),
                (
                    "alt_en",
                    models.CharField(
                        default="Photo Wood Life",
                        max_length=100,
                        verbose_name="Опис (en)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото головна сторінка",
                "verbose_name_plural": "Фото головна сторінка",
            },
        ),
    ]
