# Generated by Django 5.2.11 on 2026-02-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_gallerypage"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallerypage",
            name="category",
            field=models.CharField(
                choices=[
                    ("rooms", "Rooms"),
                    ("amenities", "Amenities"),
                    ("interior", "Interior"),
                    ("exterior", "Exterior"),
                ],
                default="rooms",
                max_length=20,
                verbose_name="Категорія",
            ),
        ),
    ]
