# Generated by Django 5.2.11 on 2026-02-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_gallerypage_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gallerypage",
            options={
                "verbose_name": "Фото галерея",
                "verbose_name_plural": "Фото галерея",
            },
        ),
        migrations.AddField(
            model_name="amenity",
            name="category",
            field=models.CharField(
                choices=[
                    ("sleeping", "Sleeping"),
                    ("technology", "Technology"),
                    ("comfort", "Comfort"),
                    ("bathroom", "Bathroom"),
                ],
                default="comfort",
                max_length=20,
                verbose_name="Категорія",
            ),
        ),
    ]
