# Generated by Django 5.2.11 on 2026-02-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_alter_gallerypage_options_amenity_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="comment_en",
            field=models.TextField(default="", verbose_name="Коментар (англ)"),
        ),
        migrations.AddField(
            model_name="room",
            name="comment_name_en",
            field=models.CharField(
                default="", max_length=100, verbose_name="Коментар Імʼя (укр)"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="comment_name_uk",
            field=models.CharField(
                default="", max_length=100, verbose_name="Коментар Імʼя (укр)"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="comment_uk",
            field=models.TextField(default="", verbose_name="Коментар (укр)"),
        ),
        migrations.AddField(
            model_name="room",
            name="has_generator",
            field=models.BooleanField(
                default=False, verbose_name="Наявність генератора"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="housekeeping_en",
            field=models.CharField(
                default="", max_length=100, verbose_name="Прибирання в котеджі (англ)"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="housekeeping_uk",
            field=models.CharField(
                default="", max_length=100, verbose_name="Прибирання в котеджі (укр)"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="lable_capacity_en",
            field=models.CharField(
                default="", max_length=100, verbose_name="Кількіть людей прописом"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="lable_capacity_uk",
            field=models.CharField(
                default="", max_length=100, verbose_name="Кількіть людей прописом"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="pets_en",
            field=models.CharField(
                default="", max_length=100, verbose_name="Тварини (англ)"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="pets_uk",
            field=models.CharField(
                default="", max_length=100, verbose_name="Тварини (укр)"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="sub_title_en",
            field=models.CharField(
                default="", max_length=200, verbose_name="Текст під назвою (англ)"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="sub_title_uk",
            field=models.CharField(
                default="", max_length=200, verbose_name="Текст під назвою (укр)"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_name_en",
            field=models.CharField(max_length=200, verbose_name="Назва котеджу (англ)"),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_name_uk",
            field=models.CharField(max_length=200, verbose_name="Назва котеджу (укр)"),
        ),
    ]
