# Generated by Django 5.2.11 on 2026-02-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_room_comment_en_room_comment_name_en_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={
                "ordering": ["order"],
                "verbose_name": "Котедж",
                "verbose_name_plural": "Котеджі",
            },
        ),
        migrations.AlterModelOptions(
            name="roomimage",
            options={
                "verbose_name": "Фото котеджу",
                "verbose_name_plural": "Фото котеджів",
            },
        ),
        migrations.AddField(
            model_name="socialmedia",
            name="youtube",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="YouTube"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="comment_name_en",
            field=models.CharField(
                default="", max_length=100, verbose_name="Коментар Імʼя (англ)"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="lable_capacity_en",
            field=models.CharField(
                default="",
                max_length=100,
                verbose_name="Кількіть людей прописом (англ)",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="lable_capacity_uk",
            field=models.CharField(
                default="", max_length=100, verbose_name="Кількіть людей прописом (укр)"
            ),
        ),
        migrations.AlterField(
            model_name="socialmedia",
            name="facebook",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="Facebook"
            ),
        ),
        migrations.AlterField(
            model_name="socialmedia",
            name="instagram",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="Instagram"
            ),
        ),
        migrations.AlterField(
            model_name="socialmedia",
            name="linkedin",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="Linked In"
            ),
        ),
        migrations.AlterField(
            model_name="socialmedia",
            name="twitter",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="Twitter (X)"
            ),
        ),
    ]
