# Generated by Django 5.2.11 on 2026-02-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_alter_room_options_alter_roomimage_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeSEO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_uk",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Title (UK)"
                    ),
                ),
                (
                    "description_uk",
                    models.TextField(blank=True, verbose_name="Description (UK)"),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Title (EN)"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="Description (EN)"),
                ),
                (
                    "og_image",
                    models.ImageField(
                        blank=True, upload_to="seo/", verbose_name="OG Image"
                    ),
                ),
            ],
        ),
    ]
