# Generated by Django 5.2.11 on 2026-02-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_homeseo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallerypage",
            name="category",
            field=models.CharField(
                choices=[
                    ("rooms", "Rooms"),
                    ("amenities", "Amenities"),
                    ("interior", "Interior"),
                    ("exterior", "Exterior"),
                    ("territory", "Territory"),
                    ("nature", "Nature"),
                ],
                default="rooms",
                max_length=20,
                verbose_name="Категорія",
            ),
        ),
    ]
